# Generated by Django 5.2.15 on 2026-06-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_type',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='status',
        ),
    ]
